export const products = [
  {
    id: "rainbow-glass-beads",
    name: "Rainbow Glass Bead Set",
    price: 299,
    oldPrice: 349,
    rating: 4.5,
    reviews: 127,
    badge: "NEW",
    description: "High quality rainbow glass beads for craft & jewelry.",
    images: ["/assets/rainbowBead.jpeg", "/assets/rainbowBead2.jpeg"],
    sku: "RGB_001",
    category: "Beads",
    stone: "Glass",
  },
  {
    id: "embroidery-thread-collection",
    name: "Embroidery Thread Collection",
    price: 399,
    oldPrice: 499,
    rating: 4.7,
    reviews: 203,
    badge: "NEW",
    description: "Premium embroidery threads with vibrant colors.",
    images: ["/assets/embroideryThread.jpeg", "/assets/embroideryThread2.jpeg"],
    sku: "ET_002",
    category: "Threads",
    stone: "Cotton",
  },
  {
    id: "wooden-bead-assortment",
    name: "Wooden Bead Assortment",
    price: 249,
    oldPrice: 299,
    rating: 4.4,
    reviews: 154,
    images: ["/assets/woodenBeads.jpeg"],
    description: "Natural wooden beads for handmade crafts.",
    sku: "WB_003",
    category: "Beads",
    stone: "Wood",
  },
  {
    id: "diy-jewelry-kit",
    name: "DIY Jewelry Making Kit",
    price: 599,
    oldPrice: 799,
    rating: 4.8,
    reviews: 198,
    badge: "NEW",
    description: "Complete DIY jewelry kit for beginners.",
    images: ["/assets/DIYJewelry.jpeg"],
    sku: "DIY_004",
    category: "Kits",
    stone: "Mixed",
  },
];
